### PR TITLE
[testbed] Replace the install method of j2cli package

### LINKED ISSUE #2696: following README.testbed.VsSetup.md fails with error ./setup-container.sh: line 49: j2: command not found
**Description**

following sonic-mgmt/docs/testbed/README.testbed.VsSetup.md fails with error ./setup-container.sh: line 49: j2: command not found

**Steps to reproduce the issue:**
1. Follow steps in [README.testbed.VsSetup.md](https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md)
2. Until step [Run the setup-container.sh in the root directory of the sonic-mgmt repository:](https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md#setup-sonic-mgmt-docker)

**Describe the results you received:**
<pre>
❯ ./setup-container.sh -n sonic-mgmt -d /data
Using default image sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt
<b>./setup-container.sh: line 49: j2: command not found</b>
Build image docker-sonic-mgmt-mghoneim from /tmp/tmp.fLd6KdrF3y ...
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/tmp.fLd6KdrF3y/Dockerfile: no such file or directory
Creating container sonic-mgmt
Unable to find image 'docker-sonic-mgmt-mghoneim:latest' locally
docker: Error response from daemon: pull access denied for docker-sonic-mgmt-mghoneim, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Container creation failed, exiting
</pre>

**Describe the results you expected:**
```
❯ ./setup-container.sh -n sonic-mgmt -d /data
Using default image sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt
Build image docker-sonic-mgmt-mghoneim from /tmp/tmp.kvVJIRn7qC ...
Sending build context to Docker daemon   7.68kB
Step 1/9 : FROM sonicdev-microsoft.azurecr.io:443/docker-sonic-mgmt
 ---> f3ea45683cb9
Step 2/9 : RUN sudo groupadd -g 1000 mghoneim
 ---> Running in 0c4328a4fa89
Removing intermediate container 0c4328a4fa89
 ---> 5449534c479d
Step 3/9 : RUN sudo useradd --shell /bin/bash -u 1000 -g 1000 -d /home/mghoneim mghoneim
 ---> Running in e0e88e9c99de
Removing intermediate container e0e88e9c99de
 ---> 4c678c346419
Step 4/9 : RUN sudo sed -i "$ a mghoneim ALL=(ALL) NOPASSWD:ALL" /etc/sudoers
 ---> Running in a7a0b252a422
Removing intermediate container a7a0b252a422
 ---> f5c2c91c4efd
Step 5/9 : RUN sudo usermod -aG sudo mghoneim
 ---> Running in 8aa36e3564f4
Removing intermediate container 8aa36e3564f4
 ---> 8fc90f659b24
Step 6/9 : USER mghoneim
 ---> Running in 1e59df23fcc0
Removing intermediate container 1e59df23fcc0
 ---> 10d7f81d661e
Step 7/9 : ADD --chown=mghoneim id_rsa /home/mghoneim/.ssh/id_rsa
 ---> 895f521f237a
Step 8/9 : ENV HOME=/home/mghoneim
 ---> Running in 978bde28e5fa
Removing intermediate container 978bde28e5fa
 ---> 94ffe8eff28b
Step 9/9 : WORKDIR /home/mghoneim
 ---> Running in a4bf33a68166
Removing intermediate container a4bf33a68166
 ---> 589e34a671f4
Successfully built 589e34a671f4
Successfully tagged docker-sonic-mgmt-mghoneim:latest
Creating container sonic-mgmt
Verifying UID and GID in container matches host
Done!

```

**Additional information you deem important:**

using j2 was added to [setup-container.sh](https://github.com/Azure/sonic-mgmt/blob/master/setup-container.sh) very recently around 2 months ago (10/2020). It was introduced in this PR #2360

One solution is to install [j2cli](https://github.com/kolypto/j2cli), and add it as a step to  [README.testbed.VsSetup.md](https://github.com/Azure/sonic-mgmt/blob/master/docs/testbed/README.testbed.VsSetup.md)

### PR DESCRIPTION
**Pull request by stephengzh**
### Description of PR
The j2cli package cannot be obtained from apt-get install.
Replace the apt-get install with pip install.

Summary:
Fixes #2696

### Type of change

- [x] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [ ] Test case(new/improvement)

#### What is the motivation for this PR?

When executing setup-management-network.sh, an error happend:

STEP 1: Checking for j2cli package...
j2cli not found, installing j2cli
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package j2cli

#### How did you do it?
Replace "apt-get install" with "pip install"

### CODE REVIEW

**Comment by stephengzh** [comment]
@wangxin Please review.

**Review by wangxin — APPROVED** [review]

**Comment by wangxin** [comment]
retest vsimage please

File: ansible/setup-management-network.sh [hunk 1]
```diff
@@ -11,7 +11,7 @@ echo
 echo "STEP 1: Checking for j2cli package..."
 if ! command -v j2; then
     echo "j2cli not found, installing j2cli"
-    apt-get install -y j2cli
+    pip install j2cli
```
Comment (lguohan) [inline ansible/setup-management-network.sh:14]: suggest to specify the version here, so that it won't break when j2cli upgrade and introduce some non-backward compatible feature.

Comment (wangxin) [reply ansible/setup-management-network.sh:14]: @stephengzh Can you address the comment from @lguohan?

Comment (stephengzh) [reply ansible/setup-management-network.sh:14]: @lguohan Sorry, I missed this comment before.
 "j2cli upgrade": Do you mean python2 upgrades to python3? If so, I think it is much better to specify the version as pip2 here for now.  But if python3 is applied, "pip3 install j2cli" will be applied. Or do you have some better suggestions?

Comment (wangxin) [reply ansible/setup-management-network.sh:14]: I think Guohan's suggestion is to run the pip command with package version specified like below:
```
pip install j2cli==0.3.10
```

Comment (stephengzh) [reply ansible/setup-management-network.sh:14]: Oh, I see, so we just specify j2cli version as 0.3.10 to avoid future potential break.

Comment (wangxin) [reply ansible/setup-management-network.sh:14]: Right. Stick with the current working version.

**Review by lguohan — APPROVED** [review]
